# Generated by Django 2.1.5 on 2020-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='standard',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
