# Generated by Django 2.1.5 on 2020-04-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentwebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
