# Generated by Django 2.1.5 on 2020-04-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentwebsite', '0005_remove_institute_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_class', models.CharField(default='unknown', max_length=20)),
                ('studentwebsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentwebsite.Institute')),
            ],
            options={
                'db_table': 'subject_info',
            },
        ),
    ]
