# Generated by Django 2.1.5 on 2020-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwebsite', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
