# Generated by Django 2.1.5 on 2020-04-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0002_delete_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_code', models.CharField(default='unknown', max_length=100)),
                ('institute_name', models.CharField(default='unknown', max_length=20)),
                ('profile_image', models.FileField(max_length=255, upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'institute_info',
            },
        ),
    ]
