# Generated by Django 2.1.5 on 2020-04-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_institute_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='user',
        ),
    ]
